/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    eclipse
    id("org.sonarqube") version "4.3.0.3225"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // Get CSV parser from Apache Commons
    implementation("org.apache.commons:commons-csv:1.10.0")

    // Get Log4J from Apache Commons
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
  	implementation("org.apache.logging.log4j:log4j-core:2.20.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.mattheys.VesselSimulator")
}
